default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", "5433") %>
  username: <%= ENV.fetch("PGUSER", "urv_app") %>
  password: <%= ENV.fetch("PGPASSWORD", "urv_app_password") %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "urv_development") %>

test:
  <<: *default
  database: urv_test

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "urv_production") %>
